//
// Created by mwisniewski on 4/1/20.
//

#ifndef SO2P_2_PARAMETERS_H
#define SO2P_2_PARAMETERS_H

#define NUMBER_OF_HAIRDRESSERS_PER_SALON 5
#define NUMBER_OF_SCISSORS NUMBER_OF_HAIRDRESSERS_PER_SALON
#define NUMBER_OF_CLIENTS 8
#define BREAK_TIME 200
#define CUTTING_HAIR_TIME 350
#define WORKING_DAY_TIME 15
#define NUMBER_OF_SALONS 2

#endif //SO2P_2_PARAMETERS_H
